### ISSUE TITLE
Unable to launch from prebuilt-image

### ISSUE THREAD

**Issue by niccottrell** [Kobzol/hardware-effects#6]
Hi!
I just tried `docker pull kobzol/hardware-effects` which gives me
```
Status: Image is up to date for kobzol/hardware-effects:latest
```
then `docker run --rm -it hardware-effects`  which gives me
```
Unable to find image 'hardware-effects:latest' locally
```
Am I missing a step or is there something that needs to be added to the README?

**Comment by Kobzol** [comment]
Hi, have you tried running
`docker run --rm -it kobzol/hardware-effects`?

**Comment by niccottrell** [comment]
That's better - now I get a command prompt.. Do I then need to manually launch with `./build/branch-misprediction/branch-misprediction 1` or similar?

**Comment by Kobzol** [comment]
Yes, in interactive mode you should either launch the programs directly (`./build/branch-misprediction/branch-misprediction 1`) or you can you try the Python scripts (`python3 ./branch-misprediction/benchmark.py ./build/branch-misprediction/branch-misprediction`).
